export const staticRoutes = [
    { path: '/', title: 'Home' },
    { path: '/about', title: 'About Us' },
    { path: '/blog', title: 'Blog' },
    { path: '/careers', title: 'Careers' },
    { path: '/case-studies', title: 'Case Studies' },
    { path: '/contact', title: 'Contact Us' },
    { path: '/how-we-work', title: 'How We Work' },
    { path: '/services', title: 'Services' },
    { path: '/services/digital-marketing', title: 'Digital Marketing' },
    { path: '/services/growth-strategy', title: 'Growth Strategy' },
    { path: '/services/performance-marketing', title: 'Performance Marketing' },
    { path: '/services/web-development', title: 'Web Development' },
    { path: '/digital-marketing-agency-trivandrum', title: 'Digital Marketing Agency Trivandrum' },
    { path: '/web-development-company-kerala', title: 'Web Development Company Kerala' },
    { path: '/website-projects', title: 'Website Projects' },
];
